CREATE TABLE users(
userid INTEGER,
name TEXT NOT NULL,
PRIMARY KEY(userid));

CREATE TABLE movies(
movieid INTEGER,
title TEXT NOT NULL,
PRIMARY KEY(movieid));

CREATE TABLE taginfo(
tagid INTEGER,
content TEXT NOT NULL,
PRIMARY KEY(tagid));

CREATE TABLE genres(
genreid INTEGER,
name TEXT NOT NULL,
PRIMARY KEY(genreid));

CREATE TABLE ratings(
userid INTEGER,
movieid INTEGER,
rating NUMERIC,
CHECK (rating BETWEEN 0 AND 5),
timestamp BIGINT NOT NULL,
PRIMARY KEY(userid,movieid),
FOREIGN KEY(userid) REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(movieid) REFERENCES movies ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE tags(
userid INTEGER,
movieid INTEGER,
tagid INTEGER,
timestamp BIGINT NOT NULL,
PRIMARY KEY(userid,movieid,tagid),
FOREIGN KEY(userid) REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(movieid) REFERENCES movies ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(tagid) REFERENCES taginfo ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE hasagenre(
movieid INTEGER,
genreid INTEGER,
PRIMARY KEY(movieid,genreid),
FOREIGN KEY(movieid) REFERENCES movies ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(genreid) REFERENCES genres ON DELETE CASCADE ON UPDATE CASCADE);






